# This is a basic workflow to help you get started with Actions

name: FIRST WORK FLOW

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  #push:
  #  branches: [ "main" ]
  #pull_request:
  #  branches: [ "main" ]
  #issues:
  #  type: opened,closed
  # Allows you to run this workflow manually from the Actions tab
  schedule:
     - cron: '* * * * *'
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  example_matrix:
    strategy:
      matrix:        
        os: [ubuntu-latest, windows-latest]
        node: [14,16]
        include:
          - os: windows-latest
            node: 16
            npm: 6
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
