name: matrixpoc

on:
  workflow_dispatch:

jobs:
  example_matrix:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [cat, dog]
        node: [pink, brown]
        include:
          - os: puppy
            node: green
    steps:
      - run: echo "Hello ${{ matrix.os }} ${{ matrix.node }}"

  example_job:
    runs-on: ubuntu-latest
    environment:
      name: development
    steps:
      - name: Print Secret Value
        run: env
      - name: Print Secret Value1
        env:
          MY_SECRET: ${{ secrets.PASSWORD }}
        run: |
          echo "My secret value is: $MY_SECRET"
