name: PrintGithubSecret

on: [workflow_dispatch]

jobs:
  example_job:
    runs-on: ubuntu-latest
    environment:
      name: development
    steps:
      - name: Print Environment Variables
        run: env
      - name: Print Secret Value
        env:
          MY_SECRET: ${{ secrets.PASSWORD }}
        run: |
          echo "Starting workflow with secret..."
          echo "My secret value is: $MY_SECRET"
          # Add more steps to test workflow behavior
