name: Print GitHub Variables

on: [push]

jobs:
  print_variables:
    runs-on: ubuntu-latest
    steps:
      - name: Print GitHub context
        run: |
          echo "Repository: $GITHUB_REPOSITORY"
          echo "Commit SHA: $GITHUB_SHA"
          echo "Ref: $GITHUB_REF"
          echo "Actor: $GITHUB_ACTOR"
          echo "Workflow: $GITHUB_WORKFLOW"
          echo "Workspace: $GITHUB_WORKSPACE"
          echo "Event Name: $GITHUB_EVENT_NAME"
          echo "Event Path: $GITHUB_EVENT_PATH"
