name: Reusable workflow
on:
  workflow_dispatch:
jobs:
  job1:
    uses: .github/workflows/outputsummery.yml@main
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps: 
      - run: |
           echo "Reusable workflow has executed successfully"
           echo "Welcome to GitHub Actions"
